"""Public library surface for spoken usage retrieval."""

__version__ = "0.1.0"

from .analysis import InvalidAnalysisError, UnsupportedAnalysisError
from .api import create_app
from .channels import (
    ChannelConflictError,
    ChannelNotFoundError,
    ChannelRepository,
    ChannelRepositoryError,
)
from .contracts import (
    AnalyzerInfo,
    ChannelCreate,
    ChannelRecord,
    ChannelStatistics,
    ChannelUpdate,
    CharacterRange,
    Clip,
    CorpusStatistics,
    CorpusStatus,
    DoctorReport,
    LanguageStatistics,
    LanguageStatus,
    LanguageUpdate,
    ModelRecord,
    SearchResponse,
    SearchResult,
    SemanticAlignmentGroup,
    Suggestion,
    SuggestionsResponse,
    TokenInfo,
    TranslationBatch,
    TranslationBatchCounts,
    TranslationBatchRequest,
    TranslationCacheStatistics,
    TranslationJob,
    TranslationRequest,
    TranslationResult,
    TranslationServiceStatus,
    UpdateSummary,
)
from .search import Corpus, IncompatibleIndexError, SearchError
from .service import Indexer
from .settings import Settings
from .translations import (
    GeminiTranslationProvider,
    ProviderTranslationRequest,
    ProviderTranslationResponse,
    TranslationProvider,
    TranslationProviderError,
    TranslationService,
    validate_provider_output,
)

__all__ = [
    "AnalyzerInfo",
    "ChannelCreate",
    "ChannelConflictError",
    "ChannelNotFoundError",
    "ChannelRecord",
    "ChannelRepository",
    "ChannelRepositoryError",
    "ChannelStatistics",
    "ChannelUpdate",
    "CharacterRange",
    "Clip",
    "Corpus",
    "CorpusStatistics",
    "CorpusStatus",
    "DoctorReport",
    "IncompatibleIndexError",
    "Indexer",
    "InvalidAnalysisError",
    "LanguageStatistics",
    "LanguageStatus",
    "LanguageUpdate",
    "ModelRecord",
    "SearchError",
    "SearchResponse",
    "SearchResult",
    "SemanticAlignmentGroup",
    "Settings",
    "Suggestion",
    "SuggestionsResponse",
    "TokenInfo",
    "TranslationBatch",
    "TranslationBatchCounts",
    "TranslationBatchRequest",
    "TranslationCacheStatistics",
    "TranslationJob",
    "TranslationProvider",
    "TranslationProviderError",
    "TranslationRequest",
    "TranslationResult",
    "TranslationService",
    "TranslationServiceStatus",
    "GeminiTranslationProvider",
    "ProviderTranslationRequest",
    "ProviderTranslationResponse",
    "UnsupportedAnalysisError",
    "UpdateSummary",
    "create_app",
    "validate_provider_output",
]
