import type { SearchResult } from "./types.js";

export const fixtureResult: SearchResult = {
  rank: 1,
  score: .93,
  match_type: "exact",
  matched_surface: "bronca",
  matched_lemma: "bronca",
  token_analysis: [],
  analyzer: { name: "simplemma", language: "es", package_version: "1.2.0", model_version: null, settings: {}, identity: "fixture" },
  occurrence_id: "occurrence-1",
  segment_id: "segment-1",
  source_language: "es",
  sentence: "A mí me da mucha bronca cuando pasa eso.",
  match: { text: "bronca", char_start: 17, char_end: 23, accent_exact: true },
  sentence_start: 77.2,
  sentence_end: 82.4,
  clip_start: 76.85,
  clip_end: 83.05,
  segments: [
    { text: "A mí me da", start: 77.2, end: 78.5, char_start: 0, char_end: 10 },
    { text: "mucha bronca", start: 78.6, end: 80.1, char_start: 11, char_end: 23 },
    { text: "cuando pasa eso.", start: 80.2, end: 82.4, char_start: 24, char_end: 40 },
  ],
  boundary: { reason: "punctuation", confidence: 1 },
  quality_score: .94,
  video: {
    video_key: "video-1",
    provider: "youtube",
    id: "abc123",
    url: "https://youtube.test/abc123",
    title: "A conversation",
    channel_id: "channel",
    channel: "Easy Spanish",
    source_language: "es",
    varieties: ["Mexico"],
    speech_style: ["conversation"],
    duration: 120,
    thumbnail: null,
    track_id: "track-1",
    caption_kind: "manual",
    caption_language: "es",
  },
};
